const apiCode = {
  "global-e-02": "Giá trị không hợp lệ",
  "auth-s-01": "Yêu cầu đăng ký của bạn đã thành công, hãy kiểm tra email",
  "auth-s-02": "Đăng ký thành công",
  "auth-s-03": "Đăng nhập thành công",
  "auth-s-04": "Làm mới access token thành công",
  "auth-s-05": "Đăng xuất thành công",
  "auth-s-06": "Đổi mật khẩu thành công",
  "auth-s-08": "Yêu cầu thành công, hãy kiểm tra email của bạn 📧",
  "auth-s-09": "Lấy lại mật khẩu thành công, chào mừng bại trở lại 👋",
  "auth-s-10": "Lấy thông tin người dùng thành công",
  "auth-e-01": "Email đã tồn tại",
  "auth-e-02": "Email chưa đăng ký",
  "auth-e-03": "Không đủ quyền truy cập",
  "auth-e-04": "Sai mật khẩu",
  "auth-e-05": "Mã code không tìm thấy",
  "auth-e-06": "Không tìm thấy tài khoản",
  "auth-e-07": "Mật khẩu hiện tại không đúng",
  "account-s-01": "Lấy thông tin tài khoản thành công",
  "account-s-02": "Cập nhật tài khoản thành công",
  "account-s-03": "Xóa tài khoản thành công",
  "account-s-04": "Lấy danh sách tất cả người dùng thành công",
  "role-e-01": "Tài khoản đã có vai trò nông dân",
  "address-s-01": "Tạo địa chỉ mới thành công",
  "address-s-04": "Cập nhật địa chỉ thành công",
  "address-s-05": "Cập nhật địa chỉ mặc định thành công",
  "address-s-06": "Xóa địa chỉ thành công",
  "address-e-01": "Không tìm thấy địa chỉ",
  "address-e-02": "Không tìm thấy địa chỉ cần cập nhật",
  "address-e-03": "Không tìn thấy địa chỉ mặc định",
  "address-e-04":
    "Không thành công, bạn không phải là người tạo ra địa chỉ này",
};

export default apiCode;
