spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: agricultural service platform
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    access:
      secret: ${JWT_ACCESS_SECRET}
      expiration: ${JWT_ACCESS_EXPIRATION}
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      expiration: ${JWT_REFRESH_EXPIRATION}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  clientReceiveTokensPath: ${CLIENT_RECEIVE_TOKENS_PATH}
  cloudinary:
    cloud:
      name: ${CLOUDINARY_NAME}
    api:
      key: ${CLOUDINARY_API_KEY}
      secret: ${CLOUDINARY_API_SECRET}
    folder: ${CLOUDINARY_FOLDER}
  vnpay:
    tmn_code:  EUY7BOQD
    hash_secret: P6UNZ5IMP36AROUZGJJU7USMY7RQZSCD
    payment_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return_url: http://localhost:8080/api/payment/vnpay-return

server:
  port: ${PORT}
